$packages = @(
    @{
        name='winget'
        bucket='main'
        slug='main/wget'
    },
    @{
        name='oh-my-posh'
        bucket='main'
        slug='main/oh-my-posh'
    },
    @{
        name='teminal-icons'
        bucket='extras'
        slug='extras/terminal-icons'
    },
    @{
        name='7zip'
        bucket='main'
        slug='main/7zip'
    },
    @{
        name='fzf'
        bucket='main'
        slug='main/fzf'
    },
    @{
        name='git'
        bucket='main'
        slug='main/git'
    },
    @{
        name='grep'
        bucket='main'
        slug='main/grep'
    },
    @{
        name='1password-cli'
        bucket='main'
        slug='main/1password-cli'
    },
    @{
        name='vscode'
        bucket='extras'
        slug='extras/vscode'
    },
    @{
        name='pwsh'
        bucket='main'
        slug='main/pwsh'
    },
    @{
        name='hyper'
        bucket='extras'
        slug='extras/hyper'
    },
    @{
        name='nvm'
        bucket='main'
        slug='main/nvm'
    },
    @{
        name='postman'
        bucket='extras'
        slug='extras/postman'
    }
)